import React from 'react'
import { motion } from 'framer-motion'
import { ArrowLeft, Download, Share2, AlertTriangle, CheckCircle, Minus } from 'lucide-react'
import RiskGauge from './RiskGauge'

const ComparisonResult = ({ result, onReset }) => {
  const { 
    apk1, 
    apk2, 
    permission_differences, 
    permissions_only_in_apk1,
    dangerous_permission_differences,
    risk_score_difference,
    similarity_score,
    version_comparison,
    sdk_comparison
  } = result

  const getRiskDifferenceColor = (diff) => {
    if (diff > 2) return 'text-danger-400'
    if (diff > 0) return 'text-yellow-400'
    if (diff < -2) return 'text-cyber-400'
    return 'text-gray-400'
  }

  const getRiskDifferenceIcon = (diff) => {
    if (Math.abs(diff) < 0.5) return <Minus className="w-5 h-5" />
    if (diff > 0) return <AlertTriangle className="w-5 h-5" />
    return <CheckCircle className="w-5 h-5" />
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between"
      >
        <div className="flex items-center space-x-4">
          <button
            onClick={onReset}
            className="p-2 bg-gray-700 rounded-lg hover:bg-gray-600 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h1 className="text-3xl font-bold text-white">Comparison Results</h1>
            <p className="text-gray-400">Side-by-side APK analysis</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button 
            onClick={() => {
              const reportData = {
                comparison_report: {
                  timestamp: new Date().toISOString(),
                  apk1: result.apk1,
                  apk2: result.apk2,
                  risk_score_difference: result.risk_score_difference,
                  similarity_score: result.similarity_score,
                  permission_differences: result.permission_differences,
                  permissions_only_in_apk1: result.permissions_only_in_apk1,
                  dangerous_permission_differences: result.dangerous_permission_differences,
                  version_comparison: result.version_comparison,
                  sdk_comparison: result.sdk_comparison
                }
              }
              const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' })
              const url = URL.createObjectURL(blob)
              const a = document.createElement('a')
              a.href = url
              a.download = `apk_comparison_${Date.now()}.json`
              document.body.appendChild(a)
              a.click()
              document.body.removeChild(a)
              URL.revokeObjectURL(url)
            }}
            className="btn-secondary flex items-center space-x-2"
          >
            <Download className="w-4 h-4" />
            <span>Export</span>
          </button>
          <button 
            onClick={async () => {
              const shareText = `APK Comparison Report\n\n${result.apk1.filename} vs ${result.apk2.filename}\nRisk Score Difference: ${result.risk_score_difference}\nSimilarity: ${(result.similarity_score * 100).toFixed(1)}%\n\nGenerated by APKShield`
              
              if (navigator.share) {
                try {
                  await navigator.share({
                    title: 'APK Comparison Report',
                    text: shareText
                  })
                } catch (err) {
                  console.log('Share cancelled')
                }
              } else {
                try {
                  await navigator.clipboard.writeText(shareText)
                  alert('Comparison summary copied to clipboard!')
                } catch (err) {
                  console.error('Failed to copy to clipboard:', err)
                }
              }
            }}
            className="btn-secondary flex items-center space-x-2"
          >
            <Share2 className="w-4 h-4" />
            <span>Share</span>
          </button>
        </div>
      </motion.div>

      {/* Risk Comparison */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="card"
      >
        <h2 className="text-xl font-semibold text-white mb-6 text-center">
          Risk Assessment Comparison
        </h2>
        
        <div className="grid md:grid-cols-3 gap-8 items-center">
          {/* APK 1 */}
          <div className="text-center space-y-4">
            <h3 className="font-medium text-gray-300">{apk1.filename}</h3>
            <RiskGauge score={apk1.risk_score} />
            <div className="space-y-1">
              <div className="text-2xl font-bold text-white">{apk1.risk_score}/10</div>
              <div className={`font-medium ${
                apk1.verdict === 'Safe' ? 'text-cyber-500' :
                apk1.verdict === 'Suspicious' ? 'text-yellow-500' : 'text-danger-500'
              }`}>
                {apk1.verdict}
              </div>
            </div>
          </div>

          {/* Difference */}
          <div className="text-center space-y-4">
            <div className={`text-4xl font-bold ${getRiskDifferenceColor(risk_score_difference)}`}>
              {risk_score_difference > 0 ? '+' : ''}{risk_score_difference.toFixed(1)}
            </div>
            <div className="flex items-center justify-center space-x-2">
              <div className={getRiskDifferenceColor(risk_score_difference)}>
                {getRiskDifferenceIcon(risk_score_difference)}
              </div>
              <span className="text-gray-400">Risk Difference</span>
            </div>
            <div className="text-sm text-gray-500">
              {Math.abs(risk_score_difference) < 0.5 ? 'Similar Risk' :
               risk_score_difference > 0 ? 'Higher Risk' : 'Lower Risk'}
            </div>
          </div>

          {/* APK 2 */}
          <div className="text-center space-y-4">
            <h3 className="font-medium text-gray-300">{apk2.filename}</h3>
            <RiskGauge score={apk2.risk_score} />
            <div className="space-y-1">
              <div className="text-2xl font-bold text-white">{apk2.risk_score}/10</div>
              <div className={`font-medium ${
                apk2.verdict === 'Safe' ? 'text-cyber-500' :
                apk2.verdict === 'Suspicious' ? 'text-yellow-500' : 'text-danger-500'
              }`}>
                {apk2.verdict}
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* App Details Comparison */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="card"
      >
        <h2 className="text-xl font-semibold text-white mb-6">App Information</h2>
        
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="border-b border-gray-700">
                <th className="text-left py-3 text-gray-400">Property</th>
                <th className="text-left py-3 text-gray-400">{apk1.filename}</th>
                <th className="text-left py-3 text-gray-400">{apk2.filename}</th>
              </tr>
            </thead>
            <tbody className="space-y-2">
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">App Name</td>
                <td className="py-3 text-white">{apk1.app_name}</td>
                <td className="py-3 text-white">{apk2.app_name}</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">Package Name</td>
                <td className="py-3 text-white font-mono text-sm">{apk1.package_name}</td>
                <td className="py-3 text-white font-mono text-sm">{apk2.package_name}</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">Version</td>
                <td className="py-3 text-white">{apk1.version_name} ({apk1.version_code})</td>
                <td className="py-3 text-white">{apk2.version_name} ({apk2.version_code})</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">Target SDK</td>
                <td className="py-3 text-white">{apk1.target_sdk}</td>
                <td className="py-3 text-white">{apk2.target_sdk}</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">File Size</td>
                <td className="py-3 text-white">{apk1.file_size_human}</td>
                <td className="py-3 text-white">{apk2.file_size_human}</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">Permissions</td>
                <td className="py-3 text-white">{apk1.permissions.length} total</td>
                <td className="py-3 text-white">{apk2.permissions.length} total</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">Dangerous Permissions</td>
                <td className="py-3 text-white">{apk1.dangerous_permissions?.length || 0}</td>
                <td className="py-3 text-white">{apk2.dangerous_permissions?.length || 0}</td>
              </tr>
              <tr className="border-b border-gray-800">
                <td className="py-3 text-gray-300">Certificate</td>
                <td className="py-3">
                  <span className={`px-2 py-1 rounded text-xs ${
                    apk1.certificate_info.is_valid ? 'bg-cyber-500/20 text-cyber-400' : 'bg-danger-500/20 text-danger-400'
                  }`}>
                    {apk1.certificate_info.is_valid ? 'Valid' : 'Invalid'}
                  </span>
                </td>
                <td className="py-3">
                  <span className={`px-2 py-1 rounded text-xs ${
                    apk2.certificate_info.is_valid ? 'bg-cyber-500/20 text-cyber-400' : 'bg-danger-500/20 text-danger-400'
                  }`}>
                    {apk2.certificate_info.is_valid ? 'Valid' : 'Invalid'}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </motion.div>

      {/* Similarity Score */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.25 }}
        className="card"
      >
        <h2 className="text-xl font-semibold text-white mb-4">Similarity Analysis</h2>
        
        <div className="grid md:grid-cols-3 gap-6">
          <div className="text-center space-y-2">
            <div className="text-3xl font-bold text-primary-400">
              {(similarity_score * 100).toFixed(1)}%
            </div>
            <div className="text-gray-400">Permission Similarity</div>
          </div>
          
          {version_comparison && (
            <div className="text-center space-y-2">
              <div className={`text-2xl font-bold ${
                version_comparison.apk1_newer ? 'text-cyber-400' : 'text-yellow-400'
              }`}>
                {version_comparison.apk1_newer ? 'Newer' : 'Older'}
              </div>
              <div className="text-gray-400">APK1 vs APK2</div>
              <div className="text-sm text-gray-500">
                Version diff: {version_comparison.version_diff}
              </div>
            </div>
          )}
          
          {sdk_comparison && (
            <div className="text-center space-y-2">
              <div className={`text-2xl font-bold ${
                sdk_comparison.target_sdk_diff > 0 ? 'text-cyber-400' : 
                sdk_comparison.target_sdk_diff < 0 ? 'text-yellow-400' : 'text-gray-400'
              }`}>
                {sdk_comparison.target_sdk_diff > 0 ? 'Higher' : 
                 sdk_comparison.target_sdk_diff < 0 ? 'Lower' : 'Same'}
              </div>
              <div className="text-gray-400">Target SDK (APK1)</div>
              <div className="text-sm text-gray-500">
                SDK diff: {sdk_comparison.target_sdk_diff}
              </div>
            </div>
          )}
        </div>
      </motion.div>

      {/* Permission Differences */}
      {(permission_differences?.length > 0 || permissions_only_in_apk1?.length > 0 || dangerous_permission_differences?.length > 0) && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="card"
        >
          <h2 className="text-xl font-semibold text-white mb-6">Permission Differences</h2>
          
          {/* Dangerous Permission Differences */}
          {dangerous_permission_differences?.length > 0 && (
            <div className="mb-6">
              <h3 className="text-lg font-medium text-danger-400 mb-3">
                🔴 Additional Dangerous Permissions in {apk2.filename}
              </h3>
              <div className="grid md:grid-cols-2 gap-3">
                {dangerous_permission_differences.map((permission, index) => (
                  <motion.div
                    key={permission}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.1 * index }}
                    className="p-3 bg-danger-500/10 border border-danger-500/30 rounded-lg"
                  >
                    <div className="font-medium text-danger-400 text-sm">
                      {permission.replace('android.permission.', '')}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
          
          {/* Additional Permissions in APK2 */}
          {permission_differences?.length > 0 && (
            <div className="mb-6">
              <h3 className="text-lg font-medium text-yellow-400 mb-3">
                🟡 Additional Permissions in {apk2.filename}
              </h3>
              <div className="grid md:grid-cols-2 gap-3">
                {permission_differences.map((permission, index) => (
                  <motion.div
                    key={permission}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.1 * index }}
                    className="p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg"
                  >
                    <div className="font-medium text-yellow-400 text-sm">
                      {permission.replace('android.permission.', '')}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
          
          {/* Permissions Only in APK1 */}
          {permissions_only_in_apk1?.length > 0 && (
            <div>
              <h3 className="text-lg font-medium text-blue-400 mb-3">
                🔵 Permissions Only in {apk1.filename}
              </h3>
              <div className="grid md:grid-cols-2 gap-3">
                {permissions_only_in_apk1.map((permission, index) => (
                  <motion.div
                    key={permission}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.1 * index }}
                    className="p-3 bg-blue-500/10 border border-blue-500/30 rounded-lg"
                  >
                    <div className="font-medium text-blue-400 text-sm">
                      {permission.replace('android.permission.', '')}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
        </motion.div>
      )}

      {/* Summary */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.4 }}
        className="card"
      >
        <h2 className="text-xl font-semibold text-white mb-4">Summary</h2>
        
        <div className="space-y-4">
          {risk_score_difference > 2 && (
            <div className="p-4 bg-danger-500/10 border border-danger-500/30 rounded-lg">
              <p className="text-danger-400 font-medium">⚠️ Significant Risk Increase</p>
              <p className="text-gray-300 mt-1">
                The second APK shows significantly higher risk indicators. Exercise extreme caution.
              </p>
            </div>
          )}
          
          {Math.abs(risk_score_difference) < 0.5 && (
            <div className="p-4 bg-cyber-500/10 border border-cyber-500/30 rounded-lg">
              <p className="text-cyber-400 font-medium">✅ Similar Risk Profiles</p>
              <p className="text-gray-300 mt-1">
                Both APKs show similar risk characteristics with minimal differences.
              </p>
            </div>
          )}
          
          {dangerous_permission_differences?.length > 0 && (
            <div className="p-4 bg-danger-500/10 border border-danger-500/30 rounded-lg">
              <p className="text-danger-400 font-medium">🚨 Dangerous Permission Changes</p>
              <p className="text-gray-300 mt-1">
                The second APK requests {dangerous_permission_differences.length} additional dangerous permissions. 
                These could significantly impact user privacy and security.
              </p>
            </div>
          )}
          
          {permission_differences?.length > 5 && (
            <div className="p-4 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
              <p className="text-yellow-400 font-medium">⚠️ Many Additional Permissions</p>
              <p className="text-gray-300 mt-1">
                The second APK requests {permission_differences.length} additional permissions. 
                Review these carefully to ensure they're necessary.
              </p>
            </div>
          )}
          
          {similarity_score > 0.8 && (
            <div className="p-4 bg-cyber-500/10 border border-cyber-500/30 rounded-lg">
              <p className="text-cyber-400 font-medium">🔄 High Similarity</p>
              <p className="text-gray-300 mt-1">
                These APKs share {(similarity_score * 100).toFixed(1)}% of their permissions, indicating they're likely related versions.
              </p>
            </div>
          )}
          
          {version_comparison?.apk1_newer && version_comparison.version_diff > 0 && (
            <div className="p-4 bg-blue-500/10 border border-blue-500/30 rounded-lg">
              <p className="text-blue-400 font-medium">📈 Version Update</p>
              <p className="text-gray-300 mt-1">
                APK1 appears to be a newer version (version code difference: +{version_comparison.version_diff}).
              </p>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  )
}

export default ComparisonResult
